# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: piotrkilczuk
service: wrike-todoist

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.9
  memorySize: 128
  timeout: 120
  environment:
    PYTHONPATH: src/
    GCP_PROJECT_ID: ${env:GCP_PROJECT_ID}
    GCP_CLIENT_ID: ${env:GCP_CLIENT_ID}
    GCP_CLIENT_SECRET: ${env:GCP_CLIENT_SECRET}
    GOOGLE_CALENDAR_ID: ${env:GOOGLE_CALENDAR_ID}
    GOOGLE_CALENDAR_REFRESH_TOKEN: ${env:GOOGLE_CALENDAR_REFRESH_TOKEN}
    TODOIST_ACCESS_TOKEN: ${env:TODOIST_ACCESS_TOKEN}
    TODOIST_PROJECT_NAME: ${env:TODOIST_PROJECT_NAME}
    TODOIST_LABEL: ${env:TODOIST_LABEL}
    TODOIST_DEFAULT_PRIORITY: ${env:TODOIST_DEFAULT_PRIORITY}
    GITHUB_CLASSIC_TOKEN: ${env:GITHUB_CLASSIC_TOKEN}

plugins:
  - serverless-python-requirements

functions:
  sync_google_calendar_to_todoist:
    handler: handler.run_google_calendar
    reservedConcurrency: 1
    events:
      - schedule: rate(10 minutes)
  sync_harmonogram_to_todoist:
    handler: handler.run_harmonogram
    reservedConcurrency: 1
    events:
      - schedule: rate(1 day)
  sync_github_to_todoist:
    handler: handler.run_github
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
